apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-{{ .Values.env }}-{{ .Values.appName }}"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: "{{ .Values.env }}-shared"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.hostname }}"
spec:
  ingressClassName: alb
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "service-{{ .Values.appName }}"
                port:
                  number: {{ .Values.ingress.port }}
