apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-sidecar
  namespace: {{ .Values.grafana.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]