# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: adot-collector
#   namespace: {{ .Release.Namespace }}
#   labels:
#     app.kubernetes.io/name: adot-collector
#     app.kubernetes.io/component: opentelemetry-collector
# #   annotations:
# #     eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}