env: dev
clusterName: eks-dev-demo
region: us-east-1
# Value for variable below needs to be updated whenever deploying to a new environment.
# Run the following steps to get new workspace endpoint:
## cd /app/infra/aws/envs/dev/platform/eks-addons ; terragrunt output amp_workspace_endpoint
ampEndpoint: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-ca2d942c-35ec-4fa5-a1e0-011a421fb79a/api/v1/remote_write
nodeExporterEndpoint: prometheus-node-exporter.prometheus-node-exporter.svc.cluster.local:9100
kubeStateMetricsEndpoint: kube-state-metrics.kube-state-metrics.svc.cluster.local:8080
