env: dev
clusterName: eks-dev-demo
region: us-east-1
# Value for variable below needs to be updated whenever deploying to a new environment.
# Run the following steps to get new workspace endpoint:
## cd /app/infra/aws/envs/dev/platform/eks-addons ; terragrunt output amp_workspace_endpoint
ampEndpoint: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-5106f95e-31f8-4536-92a8-a804d37d2807/
