# ADOT Collector config
serviceAccount:
  roleArn: ""

amp:
  workspaceUrl: ""

receivers:
  otlp:
    grpc:
      endpoint: "0.0.0.0:4317"
    http:
      endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    enabled: true
    endpoint: "0.0.0.0:8889"
  amp:
    enabled: true
  cloudwatch:
    enabled: false
  xray:
    enabled: false

processors:
  batch:
    timeout: "5s"
    sendBatchSize: 1000
  memory_limiter:
    checkInterval: "1s"
    limitMib: 200
    spikeLimitMib: 50

# kube-prometheus-stack subchart values
kube-prometheus-stack:
  nodeExporter:
    enabled: false # already have as EKS addon
  grafana:
    enabled: true
    adminPassword: "admin"
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
      hosts:
        - grafana.studyk8s.com
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      remoteWrite:
        - url: ""
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  alertmanager:
    enabled: false
