apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: adot-collector
  namespace: opentelemetry-operator-system
spec:
  mode: deployment
  serviceAccount: opentelemetry-operator
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'node-exporter'
              scrape_interval: 30s
              kubernetes_sd_configs:
                - role: endpointslice
                  namespaces:
                    names: ['prometheus-node-exporter']
              relabel_configs:
                - source_labels: [__meta_kubernetes_endpointslice_endpoint_node_name]
                  target_label: node
                - source_labels: [__meta_kubernetes_endpointslice_endpoint_node_name]
                  target_label: instance
            - job_name: 'kube-state-metrics'
              scrape_interval: 30s
              kubernetes_sd_configs:
                - role: endpointslice
                  namespaces:
                    names: ['kube-state-metrics']
              relabel_configs:
                - source_labels: [__meta_kubernetes_endpointslice_endpoint_node_name]
                  target_label: instance
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 256
      resource:
        attributes:
          - action: insert
            key: cluster
            value: {{ .Values.clusterName }}
    exporters:
      prometheusremotewrite:
        endpoint: {{ .Values.ampEndpoint }}
        auth:
          authenticator: sigv4auth
        resource_to_telemetry_conversion:
          enabled: true
    extensions:
      sigv4auth:
        region: {{ .Values.region }}
        service: aps
    service:
      extensions: [sigv4auth]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheusremotewrite]