amp:
  endpoint: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-ca2d942c-35ec-4fa5-a1e0-011a421fb79a
  region: us-east-1

grafana:
  namespace: grafana
  hostname: grafana.studyk8s.com
  grafana.ini:
    analytics:
      check_for_updates: true
    auth:
      sigv4_auth_enabled: true
    log:
      mode: console

collector:
  serviceAccount: opentelemetry-operator
  namespace: opentelemetry-operator-system
