amp:
  endpoint: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-5106f95e-31f8-4536-92a8-a804d37d2807
  region: us-east-1

grafana:
  namespace: grafana
  hostname: grafana.studyk8s.com

collector:
  serviceAccount: opentelemetry-operator
  namespace: opentelemetry-operator-system
